version: "3.8"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
#    env_file:
#      - ./.env
    volumes:
      - ./:/code
      - "~/.aws:/home/smartcast_docker/.aws"
    command: flask run --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"
    networks:
      proxy:
        aliases:
          - smartcast_backend_service

#networks:
#  proxy:
#    external: true
#    name: smartcast-internal-network
