FROM python:3

ENV PATH=$PATH:/home/$UNAME/.local/bin

RUN python -m pip install --upgrade pip

RUN apt-get update && apt-get install -y nano bash

USER $UNAME
COPY --chown=$UNAME:$UNAME requirements.txt /code/
RUN pip install --no-cache-dir -r /code/requirements.txt
WORKDIR /code

